# Generated by Django 2.0 on 2023-07-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('category_name', models.CharField(max_length=20)),
                ('category_image', models.ImageField(upload_to='images')),
                ('category_added_date', models.DateTimeField(auto_now_add=True)),
                ('category_deleted_date', models.DateTimeField(blank=True, null=True)),
                ('category_edited_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_status', models.CharField(default=False, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruduct_name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('unit', models.CharField(choices=[('PER GK', '/kg'), ('PER LETRE', '/ltr'), ('PER QTY', '/qty')], default='PER QTY', max_length=10)),
                ('image', models.ImageField(upload_to='images')),
                ('product_quantity', models.IntegerField()),
                ('product_added_date', models.DateTimeField(auto_now_add=True)),
                ('product_expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=200)),
                ('deleted_status', models.BooleanField(default=False)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopify.Category')),
            ],
        ),
        
    ]
