# Generated by Django 2.1 on 2023-08-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_auto_20230814_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
