# Generated by Django 2.1 on 2023-08-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0006_auto_20230814_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='product_manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
