# Generated by Django 2.1 on 2023-08-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0007_items_product_manufacture_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='pruduct_name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='items',
        ),
    ]
