# Generated by Django 2.1 on 2023-09-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0012_auto_20230909_2037'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order_item',
        ),
    ]
